{{- range .Values.microservices }}
{{- if .hpa }}
{{- if .hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}-hpa
  labels:
    app: {{ .labels }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}-deploy
  minReplicas: {{ .hpa.minReplicas }}
  maxReplicas: {{ .hpa.maxReplicas }}
  metrics:
  {{- if .hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .hpa.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .hpa.behavior }}
  behavior:
    {{- if .hpa.behavior.scaleDown }}
    scaleDown:
      stabilizationWindowSeconds: {{ .hpa.behavior.scaleDown.stabilizationWindowSeconds | default 300 }}
      policies:
      {{- range .hpa.behavior.scaleDown.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    {{- end }}
    {{- if .hpa.behavior.scaleUp }}
    scaleUp:
      stabilizationWindowSeconds: {{ .hpa.behavior.scaleUp.stabilizationWindowSeconds | default 0 }}
      policies:
      {{- range .hpa.behavior.scaleUp.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
